/*
 * Copyright (c) 2026 Anatoly S. Krivitsky, Ph.D.
 * All rights reserved.
 *
 * Permission is granted, free of charge, to use, copy, distribute, and publish
 * this SQL script, provided that this copyright notice is preserved.
 *
 * This script is provided "as is", without warranty of any kind.
 */
DROP TABLE IF EXISTS book;

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(120) NOT NULL,
    isbn VARCHAR(20) NOT NULL,
    published_date DATE,
    price NUMERIC(10, 2),
    stock_quantity INTEGER NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uk_book_isbn UNIQUE (isbn),
    CONSTRAINT ck_book_price_nonnegative CHECK (price IS NULL OR price >= 0),
    CONSTRAINT ck_book_stock_nonnegative CHECK (stock_quantity >= 0)
);